version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment: 
      ENVIRONMENT: "production"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "plando_password"
      ACCEPT_EULA: "Y"
        